
CREATE SCHEMA IF NOT EXISTS dental_clinic;
SET search_path TO dental_clinic;

CREATE TABLE IF NOT EXISTS procedures (
    procedure_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procedure_name VARCHAR(100) NOT NULL UNIQUE,
    base_cost NUMERIC(8, 2) NOT NULL CHECK (base_cost >= 0)
);

CREATE TABLE IF NOT EXISTS insurance_plans (
    plan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_type VARCHAR(50) NOT NULL CHECK (plan_type IN ('No_Insurance', 'Basic_Cover', 'Premium_Dental', 'Family_Plan')),
    monthly_premium NUMERIC(6, 2) NOT NULL CHECK (monthly_premium >= 0),
    duration_months INT NOT NULL,
    total_cost NUMERIC(6, 2) GENERATED ALWAYS AS (monthly_premium * duration_months) STORED
);

CREATE TABLE IF NOT EXISTS patients (
    patient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(30) NOT NULL,
    plan_id INT,
    registration_date DATE NOT NULL CHECK (registration_date > DATE '2026-01-01'),
    FOREIGN KEY (plan_id) REFERENCES insurance_plans(plan_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS dentists (
    dentist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT UNIQUE, -- In case a staff member is also a clinic patient
    license_number VARCHAR(50) NOT NULL UNIQUE,
    specialization VARCHAR(100) NOT NULL,
    years_of_experience INT,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS appointments (
    appointment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    dentist_id INT NOT NULL,
    appointment_date DATE NOT NULL,
    FOREIGN KEY (dentist_id) REFERENCES dentists(dentist_id) ON DELETE CASCADE,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS treatment_history (
    treatment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INT,
    procedure_id INT,
    notes TEXT NOT NULL,
    cost_charged NUMERIC(8, 2) NOT NULL CHECK (cost_charged >= 0),
    FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE,
    FOREIGN KEY (procedure_id) REFERENCES procedures(procedure_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    billing_address VARCHAR(150) NOT NULL,
    is_paid VARCHAR(5) DEFAULT 'false' NOT NULL CHECK (is_paid IN ('true', 'false')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoice_items (
    invoice_id INT NOT NULL,
    treatment_id INT NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (invoice_id, treatment_id),
    FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id) ON DELETE CASCADE,
    FOREIGN KEY (treatment_id) REFERENCES treatment_history(treatment_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS patient_allergies (
    patient_id INT NOT NULL,
    allergy_name VARCHAR(100) NOT NULL,
    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (patient_id, allergy_name),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS preferred_dentists (
    patient_id INT NOT NULL,
    dentist_id INT NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (patient_id, dentist_id),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (dentist_id) REFERENCES dentists(dentist_id) ON DELETE CASCADE
);

-- Add severity rating support for emergency triage cases
ALTER TABLE treatment_history ADD COLUMN IF NOT EXISTS is_emergency BOOLEAN DEFAULT false NOT NULL;

-- Extend character limits to support international/formatted phone strings
ALTER TABLE patients ALTER COLUMN phone_number TYPE VARCHAR(100);

-- Prevent patients from scheduling duplicate records at the exact same calendar date with the same dentist
ALTER TABLE appointments DROP CONSTRAINT IF EXISTS uq_patient_dentist_date;
ALTER TABLE appointments ADD CONSTRAINT uq_patient_dentist_date UNIQUE (patient_id, dentist_id, appointment_date);

-- Fallback to general practitioner if specialization track is omitted
ALTER TABLE dentists ALTER COLUMN specialization SET DEFAULT 'General Dentistry';

-- Remove redundant internal narrative data to optimize database storage size
ALTER TABLE dentists DROP COLUMN IF EXISTS years_of_experience;


TRUNCATE TABLE patients, dentists, appointments, treatment_history, procedures, insurance_plans RESTART IDENTITY CASCADE;

INSERT INTO procedures (procedure_name, base_cost) VALUES 
('Routine Cleaning', 85.00),
('Deep Scaling', 210.00),
('Composite Filling', 150.00),
('Root Canal Therapy', 850.00),
('Porcelain Crown', 1200.00);

INSERT INTO insurance_plans (plan_type, monthly_premium, duration_months) VALUES 
('No_Insurance', 0.00, 1),
('Basic_Cover', 19.99, 12),
('Premium_Dental', 45.99, 12),
('Family_Plan', 79.99, 12),
('Premium_Dental', 39.99, 24);

INSERT INTO patients (full_name, email, phone_number, plan_id, registration_date) VALUES 
('Anuar Qali', 'anuar.q@email.com', '+7-701-111-2233', (SELECT plan_id FROM insurance_plans WHERE plan_type = 'Premium_Dental' AND monthly_premium = 45.99), '2026-03-04'),
('Nurbol Qanat', 'nurbol.q@email.com', '+7-702-444-5566', (SELECT plan_id FROM insurance_plans WHERE plan_type = 'No_Insurance'), '2026-10-10'),
('Ansar Omar', 'ansar.o@email.com', '+7-705-777-8899', (SELECT plan_id FROM insurance_plans WHERE plan_type = 'Basic_Cover'), '2026-04-14'),
('Utezhan Qasym', 'utezhan.q@email.com', '+7-707-123-4567', (SELECT plan_id FROM insurance_plans WHERE plan_type = 'Family_Plan'), '2026-12-21'),
('Rasul Oraz', 'rasul.o@email.com', '+7-747-987-6543', (SELECT plan_id FROM insurance_plans WHERE plan_type = 'Premium_Dental' AND monthly_premium = 39.99), '2026-06-10'),
('patient_to_delete', 'delete.me@email.com', '0000000000', (SELECT plan_id FROM insurance_plans WHERE plan_type = 'No_Insurance'), '2026-01-20');

INSERT INTO dentists (patient_id, license_number, specialization) VALUES 
((SELECT patient_id FROM patients WHERE email = 'utezhan.q@email.com'), 'DENT-2026-0091', 'Orthodontics'),
(NULL, 'DENT-2015-4412', 'Endodontics'),
(NULL, 'DENT-2018-8831', 'Periodontics'),
(NULL, 'DENT-2021-3055', 'Oral Surgery'),
(NULL, 'DENT-2010-1102', 'Prosthodontics');

INSERT INTO appointments (patient_id, dentist_id, appointment_date) VALUES 
((SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2026-0091'), '2026-03-20'),
((SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2026-0091'), '2026-11-25'),
((SELECT patient_id FROM patients WHERE email = 'nurbol.q@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2015-4412'), '2026-10-15'),
((SELECT patient_id FROM patients WHERE email = 'ansar.o@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2021-3055'), '2026-04-24'),
((SELECT patient_id FROM patients WHERE email = 'rasul.o@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2010-1102'), '2026-06-16');

INSERT INTO treatment_history (appointment_id, procedure_id, notes, cost_charged) VALUES 
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-03-20' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Routine Cleaning'), 'Standard bi-annual hygiene scaling executed.', 85.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-03-20' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Composite Filling'), 'Decay removed from tooth #14, composite resin setting.', 150.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-11-25' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Routine Cleaning'), 'Follow-up observation clean.', 85.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-10-15' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'nurbol.q@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Root Canal Therapy'), 'Complex root canal isolation on lower molar.', 850.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-10-15' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'nurbol.q@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Porcelain Crown'), 'Temporary mold prepared for future permanent crown installation.', 1200.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-04-24' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'ansar.o@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Deep Scaling'), 'Tarter removal performed under local anesthesia block.', 210.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-04-24' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'ansar.o@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Composite Filling'), 'Secondary cavity patched on tooth #3.', 150.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-06-16' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'rasul.o@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Porcelain Crown'), 'Permanent porcelain fit adjustment and final bonding.', 1200.00),
((SELECT appointment_id FROM appointments WHERE appointment_date = '2026-06-16' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'rasul.o@email.com')), (SELECT procedure_id FROM procedures WHERE procedure_name = 'Routine Cleaning'), 'Polishing sequence finished.', 85.00);

INSERT INTO invoices (patient_id, billing_address, is_paid) VALUES 
((SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com'), '71 Qazaqstan Str, Astana', 'false'),
((SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com'), '71 Qazaqstan Str, Astana', 'true'),
((SELECT patient_id FROM patients WHERE email = 'nurbol.q@email.com'), '12 Mangilik El Ave, Almaty', 'false'),
((SELECT patient_id FROM patients WHERE email = 'ansar.o@email.com'), '305 Abay Road, Shymkent', 'false'),
((SELECT patient_id FROM patients WHERE email = 'rasul.o@email.com'), '88 Dostyk Block, Atyrau', 'true');

INSERT INTO invoice_items (invoice_id, treatment_id) VALUES 
((SELECT invoice_id FROM invoices WHERE billing_address = '71 Qazaqstan Str, Astana' LIMIT 1), (SELECT treatment_id FROM treatment_history WHERE cost_charged = 85.00 AND appointment_id = (SELECT appointment_id FROM appointments WHERE appointment_date = '2026-03-20' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com')))),
((SELECT invoice_id FROM invoices WHERE billing_address = '71 Qazaqstan Str, Astana' LIMIT 1), (SELECT treatment_id FROM treatment_history WHERE cost_charged = 150.00 AND appointment_id = (SELECT appointment_id FROM appointments WHERE appointment_date = '2026-03-20' AND patient_id = (SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com')))),
((SELECT invoice_id FROM invoices WHERE billing_address = '71 Qazaqstan Str, Astana' OFFSET 1 LIMIT 1), (SELECT treatment_id FROM treatment_history WHERE cost_charged = 85.00 AND appointment_id = (SELECT appointment_id FROM appointments WHERE appointment_date = '2026-11-25'))),
((SELECT invoice_id FROM invoices WHERE billing_address = '12 Mangilik El Ave, Almaty'), (SELECT treatment_id FROM treatment_history WHERE cost_charged = 850.00)),
((SELECT invoice_id FROM invoices WHERE billing_address = '12 Mangilik El Ave, Almaty'), (SELECT treatment_id FROM treatment_history WHERE cost_charged = 1200.00 AND appointment_id = (SELECT appointment_id FROM appointments WHERE patient_id = (SELECT patient_id FROM patients WHERE email = 'nurbol.q@email.com'))));

INSERT INTO preferred_dentists (patient_id, dentist_id) VALUES 
((SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2026-0091')),
((SELECT patient_id FROM patients WHERE email = 'nurbol.q@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2018-8831')),
((SELECT patient_id FROM patients WHERE email = 'ansar.o@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2021-3055')),
((SELECT patient_id FROM patients WHERE email = 'rasul.o@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2010-1102')),
((SELECT patient_id FROM patients WHERE email = 'anuar.q@email.com'), (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2015-4412'));

INSERT INTO patient_allergies (patient_id, allergy_name) 
SELECT p.patient_id, allergy 
FROM patients p 
CROSS JOIN (VALUES ('Penicillin'), ('Latex'), ('Local Anesthetics (Lidocaine)')) AS a(allergy)
WHERE p.email = 'anuar.q@email.com';

INSERT INTO patient_allergies (patient_id, allergy_name) 
SELECT p.patient_id, allergy 
FROM patients p 
CROSS JOIN (VALUES ('Codeine'), ('Sulfa Drugs')) AS a(allergy)
WHERE p.email = 'nurbol.q@email.com';

-- FIXED: We drop the roles first if they exist. This implicitly wipes any grants cleanly.
DROP ROLE IF EXISTS dental_readonly;
DROP ROLE IF EXISTS dental_writer;

-- Creating roles clean
CREATE ROLE dental_readonly;
CREATE ROLE dental_writer;

-- Distributing schema usage rights
GRANT USAGE ON SCHEMA dental_clinic TO dental_readonly;
GRANT USAGE ON SCHEMA dental_clinic TO dental_writer;

-- Assigning concrete table permissions
GRANT SELECT ON ALL TABLES IN SCHEMA dental_clinic TO dental_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dental_clinic TO dental_writer;


UPDATE insurance_plans 
SET monthly_premium = monthly_premium * 0.90 
WHERE plan_type LIKE 'Premium_%';

UPDATE treatment_history 
SET cost_charged = cost_charged + 25.00 
WHERE appointment_id IN (SELECT appointment_id FROM appointments WHERE dentist_id = (SELECT dentist_id FROM dentists WHERE license_number = 'DENT-2026-0091'));

BEGIN;
DELETE FROM patients 
WHERE email = 'delete.me@email.com' 
RETURNING patient_id, full_name, email;
ROLLBACK;
